/* soapSoapBindingProxy.h
   Generated by gSOAP 2.8.129 for ThkWCIntf.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapSoapBindingProxy_H
#define soapSoapBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC SoapBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'SoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in ThkWCIntf.h, if any
        /// Construct a proxy with new managing context
        SoapBindingProxy();
        /// Copy constructor
        SoapBindingProxy(const SoapBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        SoapBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        SoapBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        SoapBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        SoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        SoapBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        SoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~SoapBindingProxy();
        /// Initializer used by constructors
        virtual void SoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual SoapBindingProxy *copy();
        /// Copy assignment
        SoapBindingProxy& operator=(const SoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'ExecuteSoapJmsRPC' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ExecuteSoapJmsRPC(std::string &Collection) { return this->ExecuteSoapJmsRPC(NULL, NULL, Collection); }
        /// Web service synchronous operation 'ExecuteSoapJmsRPC' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ExecuteSoapJmsRPC(const char *soap_endpoint_url, const char *soap_action, std::string &Collection) { return this->send_ExecuteSoapJmsRPC(soap_endpoint_url, soap_action) || this->recv_ExecuteSoapJmsRPC(Collection) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ExecuteSoapJmsRPC' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ExecuteSoapJmsRPC(const char *soap_endpoint_url, const char *soap_action);
        /// Web service asynchronous operation 'recv_ExecuteSoapJmsRPC' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ExecuteSoapJmsRPC(std::string &Collection);
        //
        /// Web service synchronous operation 'GetWSDL' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetWSDL(std::string &Collection) { return this->GetWSDL(NULL, NULL, Collection); }
        /// Web service synchronous operation 'GetWSDL' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetWSDL(const char *soap_endpoint_url, const char *soap_action, std::string &Collection) { return this->send_GetWSDL(soap_endpoint_url, soap_action) || this->recv_GetWSDL(Collection) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetWSDL' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetWSDL(const char *soap_endpoint_url, const char *soap_action);
        /// Web service asynchronous operation 'recv_GetWSDL' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetWSDL(std::string &Collection);
        //
        /// Web service synchronous operation 'jmsexample' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int jmsexample(const std::string& arg1, const std::string& arg2, std::string &Collection) { return this->jmsexample(NULL, NULL, arg1, arg2, Collection); }
        /// Web service synchronous operation 'jmsexample' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int jmsexample(const char *soap_endpoint_url, const char *soap_action, const std::string& arg1, const std::string& arg2, std::string &Collection) { return this->send_jmsexample(soap_endpoint_url, soap_action, arg1, arg2) || this->recv_jmsexample(Collection) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_jmsexample' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_jmsexample(const char *soap_endpoint_url, const char *soap_action, const std::string& arg1, const std::string& arg2);
        /// Web service asynchronous operation 'recv_jmsexample' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_jmsexample(std::string &Collection);
        //
        /// Web service synchronous operation 'ping' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ping(std::string &Collection) { return this->ping(NULL, NULL, Collection); }
        /// Web service synchronous operation 'ping' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ping(const char *soap_endpoint_url, const char *soap_action, std::string &Collection) { return this->send_ping(soap_endpoint_url, soap_action) || this->recv_ping(Collection) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ping' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ping(const char *soap_endpoint_url, const char *soap_action);
        /// Web service asynchronous operation 'recv_ping' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ping(std::string &Collection);
        //
        /// Web service synchronous operation 'findModelByName' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int findModelByName(const std::string& partNumber, std::string &Collection) { return this->findModelByName(NULL, NULL, partNumber, Collection); }
        /// Web service synchronous operation 'findModelByName' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int findModelByName(const char *soap_endpoint_url, const char *soap_action, const std::string& partNumber, std::string &Collection) { return this->send_findModelByName(soap_endpoint_url, soap_action, partNumber) || this->recv_findModelByName(Collection) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_findModelByName' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_findModelByName(const char *soap_endpoint_url, const char *soap_action, const std::string& partNumber);
        /// Web service asynchronous operation 'recv_findModelByName' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_findModelByName(std::string &Collection);
        //
        /// Web service synchronous operation 'findModelStreamByName' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int findModelStreamByName(const std::string& partNumber, std::string &Collection) { return this->findModelStreamByName(NULL, NULL, partNumber, Collection); }
        /// Web service synchronous operation 'findModelStreamByName' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int findModelStreamByName(const char *soap_endpoint_url, const char *soap_action, const std::string& partNumber, std::string &Collection) { return this->send_findModelStreamByName(soap_endpoint_url, soap_action, partNumber) || this->recv_findModelStreamByName(Collection) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_findModelStreamByName' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_findModelStreamByName(const char *soap_endpoint_url, const char *soap_action, const std::string& partNumber);
        /// Web service asynchronous operation 'recv_findModelStreamByName' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_findModelStreamByName(std::string &Collection);
    };
#endif
