/* soapStub.h
   Generated by gSOAP 2.8.129 for ThkWCIntf.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"http://www.ptc.com/infoengine/soap/rpc/message/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208129
# error "GSOAP VERSION 208129 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/* dom.h:62 */
#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (9)
typedef struct soap_dom_element xsd__anyType;
#endif

/* dom.h:65 */
#ifndef SOAP_TYPE_xsd__anyAttribute
#define SOAP_TYPE_xsd__anyAttribute (11)
typedef struct soap_dom_attribute xsd__anyAttribute;
#endif

/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

struct ns1__ExecuteSoapJmsRPCResponse;	/* ThkWCIntf.h:327 */
struct ns1__ExecuteSoapJmsRPC;	/* ThkWCIntf.h:327 */
struct ns1__GetWSDLResponse;	/* ThkWCIntf.h:397 */
struct ns1__GetWSDL;	/* ThkWCIntf.h:397 */
struct ns1__jmsexampleResponse;	/* ThkWCIntf.h:471 */
struct ns1__jmsexample;	/* ThkWCIntf.h:471 */
struct ns1__pingResponse;	/* ThkWCIntf.h:545 */
struct ns1__ping;	/* ThkWCIntf.h:545 */
struct ns1__findModelByNameResponse;	/* ThkWCIntf.h:615 */
struct ns1__findModelByName;	/* ThkWCIntf.h:615 */
struct ns1__findModelStreamByNameResponse;	/* ThkWCIntf.h:685 */
struct ns1__findModelStreamByName;	/* ThkWCIntf.h:685 */

/* ThkWCIntf.h:327 */
#ifndef SOAP_TYPE_ns1__ExecuteSoapJmsRPCResponse
#define SOAP_TYPE_ns1__ExecuteSoapJmsRPCResponse (15)
/* complex XML schema type 'ns1:ExecuteSoapJmsRPCResponse': */
struct SOAP_CMAC ns1__ExecuteSoapJmsRPCResponse {
      public:
        /** Required element 'Collection' of XML schema type 'xsd:string' */
        std::string Collection;
      public:
        /** Return unique type id SOAP_TYPE_ns1__ExecuteSoapJmsRPCResponse */
        long soap_type() const { return SOAP_TYPE_ns1__ExecuteSoapJmsRPCResponse; }
        /** Constructor with member initializations */
        ns1__ExecuteSoapJmsRPCResponse() : Collection() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__ExecuteSoapJmsRPCResponse * SOAP_FMAC2 soap_instantiate_ns1__ExecuteSoapJmsRPCResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:327 */
#ifndef SOAP_TYPE_ns1__ExecuteSoapJmsRPC
#define SOAP_TYPE_ns1__ExecuteSoapJmsRPC (16)
/* complex XML schema type 'ns1:ExecuteSoapJmsRPC': */
struct SOAP_CMAC ns1__ExecuteSoapJmsRPC {
      public:
        /** Return unique type id SOAP_TYPE_ns1__ExecuteSoapJmsRPC */
        long soap_type() const { return SOAP_TYPE_ns1__ExecuteSoapJmsRPC; }
        /** Constructor with member initializations */
        ns1__ExecuteSoapJmsRPC() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__ExecuteSoapJmsRPC * SOAP_FMAC2 soap_instantiate_ns1__ExecuteSoapJmsRPC(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:397 */
#ifndef SOAP_TYPE_ns1__GetWSDLResponse
#define SOAP_TYPE_ns1__GetWSDLResponse (18)
/* complex XML schema type 'ns1:GetWSDLResponse': */
struct SOAP_CMAC ns1__GetWSDLResponse {
      public:
        /** Required element 'Collection' of XML schema type 'xsd:string' */
        std::string Collection;
      public:
        /** Return unique type id SOAP_TYPE_ns1__GetWSDLResponse */
        long soap_type() const { return SOAP_TYPE_ns1__GetWSDLResponse; }
        /** Constructor with member initializations */
        ns1__GetWSDLResponse() : Collection() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__GetWSDLResponse * SOAP_FMAC2 soap_instantiate_ns1__GetWSDLResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:397 */
#ifndef SOAP_TYPE_ns1__GetWSDL
#define SOAP_TYPE_ns1__GetWSDL (19)
/* complex XML schema type 'ns1:GetWSDL': */
struct SOAP_CMAC ns1__GetWSDL {
      public:
        /** Return unique type id SOAP_TYPE_ns1__GetWSDL */
        long soap_type() const { return SOAP_TYPE_ns1__GetWSDL; }
        /** Constructor with member initializations */
        ns1__GetWSDL() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__GetWSDL * SOAP_FMAC2 soap_instantiate_ns1__GetWSDL(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:471 */
#ifndef SOAP_TYPE_ns1__jmsexampleResponse
#define SOAP_TYPE_ns1__jmsexampleResponse (21)
/* complex XML schema type 'ns1:jmsexampleResponse': */
struct SOAP_CMAC ns1__jmsexampleResponse {
      public:
        /** Required element 'Collection' of XML schema type 'xsd:string' */
        std::string Collection;
      public:
        /** Return unique type id SOAP_TYPE_ns1__jmsexampleResponse */
        long soap_type() const { return SOAP_TYPE_ns1__jmsexampleResponse; }
        /** Constructor with member initializations */
        ns1__jmsexampleResponse() : Collection() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__jmsexampleResponse * SOAP_FMAC2 soap_instantiate_ns1__jmsexampleResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:471 */
#ifndef SOAP_TYPE_ns1__jmsexample
#define SOAP_TYPE_ns1__jmsexample (22)
/* complex XML schema type 'ns1:jmsexample': */
struct SOAP_CMAC ns1__jmsexample {
      public:
        /** Required element 'arg1' of XML schema type 'xsd:string' */
        std::string arg1;
        /** Required element 'arg2' of XML schema type 'xsd:string' */
        std::string arg2;
      public:
        /** Return unique type id SOAP_TYPE_ns1__jmsexample */
        long soap_type() const { return SOAP_TYPE_ns1__jmsexample; }
        /** Constructor with member initializations */
        ns1__jmsexample() : arg1(), arg2() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__jmsexample * SOAP_FMAC2 soap_instantiate_ns1__jmsexample(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:545 */
#ifndef SOAP_TYPE_ns1__pingResponse
#define SOAP_TYPE_ns1__pingResponse (24)
/* complex XML schema type 'ns1:pingResponse': */
struct SOAP_CMAC ns1__pingResponse {
      public:
        /** Required element 'Collection' of XML schema type 'xsd:string' */
        std::string Collection;
      public:
        /** Return unique type id SOAP_TYPE_ns1__pingResponse */
        long soap_type() const { return SOAP_TYPE_ns1__pingResponse; }
        /** Constructor with member initializations */
        ns1__pingResponse() : Collection() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__pingResponse * SOAP_FMAC2 soap_instantiate_ns1__pingResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:545 */
#ifndef SOAP_TYPE_ns1__ping
#define SOAP_TYPE_ns1__ping (25)
/* complex XML schema type 'ns1:ping': */
struct SOAP_CMAC ns1__ping {
      public:
        /** Return unique type id SOAP_TYPE_ns1__ping */
        long soap_type() const { return SOAP_TYPE_ns1__ping; }
        /** Constructor with member initializations */
        ns1__ping() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__ping * SOAP_FMAC2 soap_instantiate_ns1__ping(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:615 */
#ifndef SOAP_TYPE_ns1__findModelByNameResponse
#define SOAP_TYPE_ns1__findModelByNameResponse (27)
/* complex XML schema type 'ns1:findModelByNameResponse': */
struct SOAP_CMAC ns1__findModelByNameResponse {
      public:
        /** Required element 'Collection' of XML schema type 'xsd:string' */
        std::string Collection;
      public:
        /** Return unique type id SOAP_TYPE_ns1__findModelByNameResponse */
        long soap_type() const { return SOAP_TYPE_ns1__findModelByNameResponse; }
        /** Constructor with member initializations */
        ns1__findModelByNameResponse() : Collection() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__findModelByNameResponse * SOAP_FMAC2 soap_instantiate_ns1__findModelByNameResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:615 */
#ifndef SOAP_TYPE_ns1__findModelByName
#define SOAP_TYPE_ns1__findModelByName (28)
/* complex XML schema type 'ns1:findModelByName': */
struct SOAP_CMAC ns1__findModelByName {
      public:
        /** Required element 'partNumber' of XML schema type 'xsd:string' */
        std::string partNumber;
      public:
        /** Return unique type id SOAP_TYPE_ns1__findModelByName */
        long soap_type() const { return SOAP_TYPE_ns1__findModelByName; }
        /** Constructor with member initializations */
        ns1__findModelByName() : partNumber() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__findModelByName * SOAP_FMAC2 soap_instantiate_ns1__findModelByName(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:685 */
#ifndef SOAP_TYPE_ns1__findModelStreamByNameResponse
#define SOAP_TYPE_ns1__findModelStreamByNameResponse (30)
/* complex XML schema type 'ns1:findModelStreamByNameResponse': */
struct SOAP_CMAC ns1__findModelStreamByNameResponse {
      public:
        /** Required element 'Collection' of XML schema type 'xsd:string' */
        std::string Collection;
      public:
        /** Return unique type id SOAP_TYPE_ns1__findModelStreamByNameResponse */
        long soap_type() const { return SOAP_TYPE_ns1__findModelStreamByNameResponse; }
        /** Constructor with member initializations */
        ns1__findModelStreamByNameResponse() : Collection() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__findModelStreamByNameResponse * SOAP_FMAC2 soap_instantiate_ns1__findModelStreamByNameResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:685 */
#ifndef SOAP_TYPE_ns1__findModelStreamByName
#define SOAP_TYPE_ns1__findModelStreamByName (31)
/* complex XML schema type 'ns1:findModelStreamByName': */
struct SOAP_CMAC ns1__findModelStreamByName {
      public:
        /** Required element 'partNumber' of XML schema type 'xsd:string' */
        std::string partNumber;
      public:
        /** Return unique type id SOAP_TYPE_ns1__findModelStreamByName */
        long soap_type() const { return SOAP_TYPE_ns1__findModelStreamByName; }
        /** Constructor with member initializations */
        ns1__findModelStreamByName() : partNumber() { }
        /** Friend allocator */
        friend SOAP_FMAC1 ns1__findModelStreamByName * SOAP_FMAC2 soap_instantiate_ns1__findModelStreamByName(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ThkWCIntf.h:746 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (32)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* ThkWCIntf.h:746 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (33)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* ThkWCIntf.h:746 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (35)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* ThkWCIntf.h:746 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* ThkWCIntf.h:746 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* std::string has binding name 'std__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (12)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (35)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (33)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (32)
#endif

/* struct ns1__findModelStreamByName has binding name 'ns1__findModelStreamByName' for type 'ns1:findModelStreamByName' */
#ifndef SOAP_TYPE_ns1__findModelStreamByName
#define SOAP_TYPE_ns1__findModelStreamByName (31)
#endif

/* struct ns1__findModelStreamByNameResponse has binding name 'ns1__findModelStreamByNameResponse' for type 'ns1:findModelStreamByNameResponse' */
#ifndef SOAP_TYPE_ns1__findModelStreamByNameResponse
#define SOAP_TYPE_ns1__findModelStreamByNameResponse (30)
#endif

/* struct ns1__findModelByName has binding name 'ns1__findModelByName' for type 'ns1:findModelByName' */
#ifndef SOAP_TYPE_ns1__findModelByName
#define SOAP_TYPE_ns1__findModelByName (28)
#endif

/* struct ns1__findModelByNameResponse has binding name 'ns1__findModelByNameResponse' for type 'ns1:findModelByNameResponse' */
#ifndef SOAP_TYPE_ns1__findModelByNameResponse
#define SOAP_TYPE_ns1__findModelByNameResponse (27)
#endif

/* struct ns1__ping has binding name 'ns1__ping' for type 'ns1:ping' */
#ifndef SOAP_TYPE_ns1__ping
#define SOAP_TYPE_ns1__ping (25)
#endif

/* struct ns1__pingResponse has binding name 'ns1__pingResponse' for type 'ns1:pingResponse' */
#ifndef SOAP_TYPE_ns1__pingResponse
#define SOAP_TYPE_ns1__pingResponse (24)
#endif

/* struct ns1__jmsexample has binding name 'ns1__jmsexample' for type 'ns1:jmsexample' */
#ifndef SOAP_TYPE_ns1__jmsexample
#define SOAP_TYPE_ns1__jmsexample (22)
#endif

/* struct ns1__jmsexampleResponse has binding name 'ns1__jmsexampleResponse' for type 'ns1:jmsexampleResponse' */
#ifndef SOAP_TYPE_ns1__jmsexampleResponse
#define SOAP_TYPE_ns1__jmsexampleResponse (21)
#endif

/* struct ns1__GetWSDL has binding name 'ns1__GetWSDL' for type 'ns1:GetWSDL' */
#ifndef SOAP_TYPE_ns1__GetWSDL
#define SOAP_TYPE_ns1__GetWSDL (19)
#endif

/* struct ns1__GetWSDLResponse has binding name 'ns1__GetWSDLResponse' for type 'ns1:GetWSDLResponse' */
#ifndef SOAP_TYPE_ns1__GetWSDLResponse
#define SOAP_TYPE_ns1__GetWSDLResponse (18)
#endif

/* struct ns1__ExecuteSoapJmsRPC has binding name 'ns1__ExecuteSoapJmsRPC' for type 'ns1:ExecuteSoapJmsRPC' */
#ifndef SOAP_TYPE_ns1__ExecuteSoapJmsRPC
#define SOAP_TYPE_ns1__ExecuteSoapJmsRPC (16)
#endif

/* struct ns1__ExecuteSoapJmsRPCResponse has binding name 'ns1__ExecuteSoapJmsRPCResponse' for type 'ns1:ExecuteSoapJmsRPCResponse' */
#ifndef SOAP_TYPE_ns1__ExecuteSoapJmsRPCResponse
#define SOAP_TYPE_ns1__ExecuteSoapJmsRPCResponse (15)
#endif

/* xsd__anyAttribute has binding name 'xsd__anyAttribute' for type 'xsd:anyAttribute' */
#ifndef SOAP_TYPE_xsd__anyAttribute
#define SOAP_TYPE_xsd__anyAttribute (11)
#endif

/* xsd__anyType has binding name 'xsd__anyType' for type 'xsd:anyType' */
#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (9)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (41)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (40)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (34)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
